# Generated by Django 5.1.6 on 2025-03-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_familymember_age_familymember_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
    ]
